project:
  type: website
  output-dir: _site

website:
  title: "Daniel Kwan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About
  page-footer:
    left: "Built with Quarto"
    right: "Copyright 2026"
  repo-url: https://github.com/daniel-kwan/dk-portfolio
  repo-actions: [edit, issue]

format:
  html:
    theme: solar
    css: styles.css
    toc: true
    link-external-newwindow: true
